config/routes.rb
Rails.application.routes.draw do
 
  root 'static_pages#home'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :assets
  resources :owners, only: [:create]
  resources :vendors, only: [:create]
  resources :orders, only: [:create]

  get '/assets/:id/deactivate', to: 'assets#deactivate', as: :deactivate
  get '/assets/:id/history', to: 'assets#history', as: :history
  
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :assets
	has_many :orders
	
	before_save { self.email = email.downcase}
	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
	validates :employee_id, presence: true, uniqueness: true
	has_secure_password
	validates :password, length: {minimum: 6}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :show]
  before_action :correct_user, only: [:edit, :update, :show]

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(admin_params)
  	if @user.save
      if @user.admin == true
        log_in @user
        flash[:success] = "Welcome to the AMS!"
  		  redirect_to @user
      else
        flash[:info] ="Employee Portal is under construction!! Visit us sometime later!"
        redirect_to root_path
      end
  	else
  		render 'new'
  	end
  end

  def show
    @vendor = Vendor.new
    @owner = Owner.new

    initialiseGONvariables
    
  	@user = User.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: AssetDatatable.new(view_context) }
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile Updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
  	def user_params
  		params.require(:user).permit(:name, :employee_id, :email, :password, :password_confirmation)
  	end

    def admin_params
      params.require(:user).permit(:name, :employee_id, :email, :password, :password_confirmation, :admin)
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in"
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to( current_user ) unless @user == current_user
    end

    def initialiseGONvariables
      assets = User.find_by(id: params[:id]).assets.where(deactivate: false)
      gon.assetList = Set.new
      gon.typeList = Set.new
      gon.ownerList = Set.new
      gon.statusList = Set.new
      gon.assignedToList = Set.new 
      gon.vendorList = Set.new
      assets.each do |asset|
        gon.assetList << asset.name
        gon.typeList << asset.asset_type
        if !asset.owner.nil?
          gon.ownerList << { value: asset.owner.id, label: asset.owner.name}
        end
        gon.statusList << asset.status
        if !asset.user.nil?
          gon.assignedToList << { value: asset.user.id, label: asset.user.name}
        end
        if !asset.vendor.nil?
          gon.vendorList << { value: asset.vendor.id, label: asset.vendor.name}
        end
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, "Edit User") %>
<h1>Update your profile</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @user do |f| %>
		  <%= render 'shared/error_messages' %>

		  <%= f.label :name, "Name" %>
		  <%= f.text_field :name, class: 'form-control' %>

		  <%= f.label :employee_id, "Employee Id" %>
		  <%= f.text_field :employee_id, class: 'form-control' %>

		  <%= f.label :email, "Email" %>
		  <%= f.text_field :email, class: 'form-control' %>

		  <%= f.label :password, "Password" %>
		  <%= f.password_field :password, class: 'form-control' %>

		  <%= f.label :password_confirmation, "Confirmation" %>
		  <%= f.password_field :password_confirmation, class: 'form-control' %>

		  <%= f.submit "Save", class: "btn btn-primary" %>
		<% end %>
		
	</div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :employee_id, "Employee ID" %>
      <%= f.text_field :employee_id, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.label :admin %>
      <%= f.check_box :admin, class: 'form-control'%>
      <br/>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div style="width: 50%; margin: 0 auto;">
<%= link_to "Add Asset", new_asset_path, class: "btn btn-default" %>
<button class="btn btn-default" data-toggle="modal" data-target="#ownerModal">Create Owner</button>

<button class="btn btn-default" data-toggle="modal" data-target="#vendorModal">Create Vendor</button>
</br></br>
</div>

<%= render 'vendors/vendor' %>
<%= render 'owners/owner' %>
<%= render 'assets/asset' %>
<%= render 'assets/history' %>