config/routes.rb
Rails.application.routes.draw do
 
  root 'static_pages#home'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :assets
  resources :owners, only: [:create]
  resources :vendors, only: [:create]
  resources :orders, only: [:create]

  get '/assets/:id/deactivate', to: 'assets#deactivate', as: :deactivate
  get '/assets/:id/history', to: 'assets#history', as: :history
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="#">Asset Management Application</a>
    by <a href="#">Sachu Thomas</a>
  </small>
  <nav>
    <ul>
      <li><a href="#">Website</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Asset Management Portal", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">        
        	<% if logged_in? %>
              <li><%= link_to "Home",  current_user %></li>
	          	<li class="dropdown">
	            	<a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= current_user.name %> <b class="caret"></b></a>
		            <ul class="dropdown-menu">
		              <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
		              <li class="divider"></li>
		              <li><%= link_to "Log out", logout_path, method: "delete" %></li>
		            </ul>
		        </li>
        	<% else %>
              <li><%= link_to "Home", root_path %></li>
          		<li><%= link_to "Log in", login_path %></li>
        	<% end %>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= include_gon %>
    <%= stylesheet_link_tag 'application', params[:controller], media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', params[:controller], 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
   <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development?   %>
    </div>
  </body>
</html>